# Generated by Django 6.1.1 on 2026-09-12 10:50

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddConstraint(
            model_name='weightentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_weight_entry_per_user_date'),
        ),
    ]
